AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'public/uploads/**/**/**/*'
    - 'config/spring.rb'
    - 'config/ansible/**/*'
    - 'config/puma/**/*'
  DisplayCopNames: true
  StyleGuideCopsOnly: false

Metrics/LineLength:
  Max: 131

Metrics/ClassLength:
  Max: 170

Metrics/BlockLength:
  Max: 130

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 9

Metrics/CyclomaticComplexity:
  Max: 9

Style/RedundantSelf:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Enabled: false
